### ISSUE TITLE
Issue with building image from Dockerfile

### ISSUE THREAD

**Issue by gvsrini** [jhipster/jhipster-docker#20]
I get this error consistently even after several tries. All the other steps are going through fine. It is getting stuck at Step 13 always.

What could be the problem

```
npm ERR! network read ETIMEDOUT
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "gulp"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall read

```

**Comment by jdubois** [comment]
From the log you sent `This is most likely not a problem with npm itself and is related to network connectivity` so I guess your problem is that you have a network issue.
And don't forget you have a pre-built image at https://hub.docker.com/r/jdubois/jhipster-docker/ so there's no need for you to build your own image.
Anyway this isn't a JHipster issue, so I'm closing this.
