### ISSUE TITLE
grunt: command not found and bower: command not found

### ISSUE THREAD

**Issue by tunesmith** [jhipster/jhipster-docker#3]
'bower install' apparently didn't run as part of 'yo jhipster'.  This is on a mac using your boot2docker instructions.  'npm install' did run, but grunt is not a recognized command.

boot2docker: 1.3.3
docker image: 1.10.2
generator-jhipster: 1.10.2

**Comment by rasheedamir** [comment]
@jdubois I am facing the same issue.

I think we should add installation command for "bower & grunt" inside the docker file.

I can see both "bower" & "grunt" in the node_modules folder but they are not being recognized as command.

and this is what happens when I run the app with prod profile

```bash
Everything looks all right!
[INFO] bower version :
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

things start working if i install them manually; should I create a pull request?

**Comment by rasheedamir** [comment]
I have created another Dockerfile which comes with all dependencies required for a project based on jhipster and it can be found here: https://github.com/rasheedamir/java-web-app-docker; and this works perfect!

I will push it to dockerhub as well. ideally we should update jhipster-docker as well!
